---
version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./LicenseChecker_Frontend
      dockerfile: Dockerfile
    ports:
      - '5173:80'
    networks:
      - resus
  backend:
    container_name: backend
    build:
      context: ./LicenceChecker
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    networks:
      - resus
  fossology:
    container_name: fossology
    image: fossology/fossology:3.10.0
    platform: linux/amd64
    ports:
      - '7100:7100'
    networks:
      - resus
  license-engine:
    container_name: license-engine
    build: ./license-engine
    ports:
      - '7001:7000'
    networks:
      - resus
    environment:
      - FOSSOLOGY_ENDPOINT_BASE_PATH=http://fossology:80
networks:
  resus:
    driver: bridge
