# Nginx configuration file

log_format navigation '$remote_addr "$http_x_forwarded_for" [$time_local] "$request_uri"';

server {
listen 80;
server_name localhost;
root /usr/share/nginx/html;
index index.html index.htm;

location = /log {
    access_log /var/log/nginx/navigation.log navigation;
    add_header Content-Length 0;
    return 204;
}

location / {
try_files $uri $uri/ /index.html;
}
}
